# Generated by Django 5.0 on 2023-12-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
