# Generated by Django 5.0 on 2023-12-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='nigga be empty'),
        ),
    ]
