# Generated by Django 5.0 on 2023-12-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0002_alter_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Seller',
            new_name='seller',
        ),
    ]
